MODEL:
  #PRETRAIN_PATH2: 'logs/softmax/resnet50_model_120.pth'
  #PRETRAIN_PATH2: 'logs/softmax/resnet50_optimizer_120.pth'
  #PRETRAIN_PATH: '/root/.torch/models/resnet50-19c8e357.pth'
  #PRETRAIN_PATH: 'model_file/market_resnet50_model_120_rank1_945.pth'
  #METRIC_LOSS_TYPE: 'softmax'
  PRETRAIN_PATH: '/root/.torch/models/se_resnet50-ce0d4300.pth'
  NAME: 'se_resnet50'

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('market1501')

DATALOADER:
  SAMPLER: 'softmax'
  NUM_WORKERS: 8
  NUM_INSTANCE: 4

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 300
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [20, 40, 55]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 10
  EVAL_PERIOD: 5

TEST:
  IMS_PER_BATCH: 64

OUTPUT_DIR: "/data2/zhihui/my/reid_strong_baseline/logs/softmax_se_resnet50_id_balance_adam2/"


